[project]
name = "linkedin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-experimental>=0.4.1",
    "langchain-google-genai>=4.0.0",
    "streamlit>=1.52.1",
    "tabulate>=0.9.0",
]
